version: '3'
services:
  web:
    build: site
    ports :
     - "81:80"
    volumes:
     - ./www:/var/www/html/
#     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
#     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: esgi_s2_bdd
      POSTGRES_USER: nimda
      POSTGRES_PASSWORD: nimdaesgi
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
